language: node_js
node_js: "8.11"

install:
  - yarn install

script:
  - yarn run build

cache: yarn

deploy:
  provider: npm
  email: "niklas.gruhn@gmail.com"
  tag: alpha
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
